export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS'
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR'
export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST' 

export const LOAD_MORE_MOVIES = 'LOAD_MORE_MOVIES'